curriculum/urls.py
from django.urls import path
from . import views

app_name='curriculum'
urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(),name='lesson_delete'),

]

sms01/urls.py
from django.contrib import admin
from django.urls import path
import sms_users
from django.conf.urls import include
import curriculum

""" from django.views.static import serve
from django.conf.urls import url """


urlpatterns = [
    path('', include('sms_users.urls')),
    path('admin/', admin.site.urls),
    path('curriculum/', include('curriculum.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

sms_users/urls.py
from django.urls import path
from . import views


# app_name = 'sms_users'
urlpatterns = [
    path('',views.index,name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('contact/', views.ContactView.as_view(), name="contact"),
]

sms_users/models.py
from django.db import models
from django.contrib.auth.models import User
import os
from django.urls import reverse

# Create your models here.

def path_and_rename(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.user.username:
        filename = 'User_Profile_Pictures/{}.{}'.format(instance.user.username, ext)
    return os.path.join(upload_to, filename)

class UserProfileInfo(models.Model):

    #creating a relationship with user class (not inheriting)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #adding additional attributes
    bio = models.CharField(max_length=500)
    profile_pic = models.ImageField(upload_to=path_and_rename, verbose_name="Profile Picture", blank=True)
    teacher = 'teacher'
    student = 'student'
    parent = 'parent'
    user_types = [
        (teacher, 'teacher'),
        (student, 'student'),
        (parent, 'parent'),
    ]
    user_type = models.CharField(max_length=10, choices=user_types, default=student)

    def __str__(self):
        return self.user.username

class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.CharField(max_length=150)
    feedback = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('index')

sms_users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from sms_users.models import UserProfileInfo


class UserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta():
        model = User
        fields = ('username','first_name','last_name', 'email', 'password1', 'password2')

        # widgets = {
        # "password":"forms.PasswordInput()",
        # }

        labels = {
        'password1':'Password',
        'password2':'Confirm Password'
        }

class UserProfileInfoForm(forms.ModelForm):
    bio = forms.CharField(required=False)
    teacher = 'teacher'
    student = 'student'
    parent = 'parent'
    user_types = [
        (student, 'student'),
        (parent, 'parent'),
    ]
    user_type = forms.ChoiceField(required=True, choices=user_types)

    class Meta():
        model = UserProfileInfo
        fields = ('bio', 'profile_pic', 'user_type')

sms_users/views.py
from django.shortcuts import render
from sms_users.forms import UserForm, UserProfileInfoForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.views.generic import TemplateView
from curriculum.models import Standard
from .models import UserProfileInfo, Contact
from django.views.generic import CreateView



def index(request):
    return render(request,'base.html')

# Create your views here.

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT IS DEACTIVATED")
        else:
            return HttpResponse("Please use correct id and password")
            # return HttpResponseRedirect(reverse('register'))

    else:
        return render(request, 'sms_users/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))




def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            # user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'sms_users/registration.html',
                            {'registered':registered,
                             'user_form':user_form,
                             'profile_form':profile_form})

class HomeView(TemplateView):
    template_name = 'sms_users/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        standards = Standard.objects.all()
        teachers = UserProfileInfo.objects.filter(user_type='teacher')
        context['standards'] = standards
        context['teachers'] = teachers
        return context

class ContactView(CreateView):
    model = Contact
    fields = '__all__'
    template_name = 'sms_users/contact.html'

sms_users/templates/sms_users/contact.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Contact Us {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Contact Us/Feedback </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li class="disabled-text" >Contact(Feedback)</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4>
  </div>
</header>
{% endblock %}

{% block content %}
<section class="text-center mt-5">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Did We Impress You?</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text">Do let our team know what you feel about this web template for school learning management. This is our attempt
                  to develop a compelte website using django and python. Your feedback or comments will be valuable to the team.</p>
                </div>
              </div>
</section>
              <div class="row justify content center">
              <div class="col-md-12">
                  <form method="post">
                    <div class="form-group">
                      {% csrf_token %}
                      {{form|crispy}}
                      <input type="submit" value="Submit Response" class="btn btn-success btn-lg btn-block">
                    </div>
                  </form>
              </div>
              </div>

{% endblock %}

sms_users/templates/sms_users/index.html
{% extends 'base.html'  %}
{% load static %}
{%block title %}index page{% endblock%}

{% block image_block%}
<header>
<!--Image and mask-->
          <div id="intro" class="container-fluid d-flex align-items-center justify-content-center h-100">
            <div class="row d-flex justify-content-center text-center">
              <div class="col-md-10 text-white">
                <!-- heading -->
                <h2 class="display-4 font-weight-bold white-text  p-5 mb-2" style="color:#ff5722;" > Start Learning </h2>

                <!-- divider -->
                <hr style="color:#ff5722;">

                <!-- description -->
                <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                          Deleniti
                          consequuntur.</h4>
                <a href="{% url 'curriculum:standard_list' %}"> <button type="button" class="btn" style="color:#ff5722;border-color:#ff5722;"> Start Now</button> </a>

                <!-- feedback and github -->
                <div class="row d-flex mt-5 justify-content-center text-center">
                  <div class="col">
                    <a href="contact"> <button type="button" class="btn" style="color:#ff5722;border-color:#ff5722;">Send Feedback</button> </a>
                  </div>
                  <div class="col">
                    <a href="https://github.com/somvirs57/school_learning_management"> <button type="button" class="btn" style="color:#ff5722;border-color:#ff5722;"> Get on GitHub</button> </a>
                  </div>
                  <div class="col">
                    <a href="https://www.youtube.com"> <button type="button" class="btn" style="color:#ff5722;border-color:#ff5722;"> Subscribe on Youtube</button> </a>
                  </div>
                </div>

              </div>
            </div>
          </div>

</header>
{%endblock%}

{% block content %}

<main class="mt-5">
  <div class="container">
    <!-- section 1 for standards-->

    <section class="text-center">
                  <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Dive Into Learning</h2>
                  <!-- class row for description-->
                  <div class="row d-flex justify-content-center mb-4">
                    <!-- class column -->
                    <div class="col-md-8">
                      <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                        hic
                                        provident nulla repellat
                                        facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                        est
                                        sit pariatur.</p>
                    </div>
                  </div>
                  <!-- class row2 for cards -->
                  <div class="row">
                          {% for standard in standards %}
                          <div class="col-md-4 d-flex mb-5 justify-content-center">
                            <div class="card text-center" style="width: 18rem;">
                              <div class="card-body">
                                <h4 class="card-title" style="color:#ff5722;">{{standard.name}}</h4>
                                <p class="card-text">{{standard.description|truncatechars:75}}</p>
                                {% if user.is_authenticated %}
                                <a href="{% url 'curriculum:subject_list' slug=standard.slug %}" class="btn btn-primary" style="background-color:#00bcd4;">Start Learning</a>
                                {%else%}
                                <p>Register or login to start learning</p>
                                <a href="{% url 'user_login' %}" class="btn btn-primary" style="background-color:#00bcd4;">Login</a>
                                <a href="{% url 'register' %}" class="btn btn-primary" style="background-color:#00bcd4;">Register</a>
                                {%endif%}
                              </div>
                            </div>
                          </div>
                          {% endfor %}
                  </div>
    </section>
    <hr class="my-5" style="color:#ff5722;">
    <!-- Section 2: Faculty Members -->

    <section class="text-center">
      <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Meet Our Faculty</h2>
      <div class="row d-flex justify-content-center mb-4">
          <div class="col-md-8">
            <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                              hic
                              provident nulla repellat
                              facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                              est
                              sit pariatur.</p>
          </div>
          <div class="row d-flex justify-content-center mb-3">
          {% for teacher in teachers %}
          <div class="card mb-3 mr-5 ml-3" style="max-width: 500px;">
            <div class="row no-gutters">
                      <div class="col-md-4">
                        <img src="{{teacher.profile_pic.url|default_if_none:'#'}}" class="card-img" alt="No image found">
                      </div>
                      <div class="col-md-8">
                        <div class="card-body">
                          <h5 class="card-title" style="color:#ff5722;">{{teacher.user.username}}</h5>
                          <p class="card-text">{{teacher.bio|truncatechars:75}}</p>
                          <p class="card-text"><small class="text-muted"></small></p>
                        </div>
                      </div>
            </div>
            </div>
          {% endfor %}
          </div>
      </div>
    </section>

    <hr class="my-5" style="color:#ff5722;">
  </div>

<!-- section 3 for activities -->

    <section class="text-center full-width container-fluid" id="event-section">
            <h2 class="mb-3 mt-5 font-weight-bold" style="color:#ff5722;">Upcoming Events</h2>
            <div class="row d-flex justify-content-center mb-4">
                <div class="col-md-8">
                  <p class="text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                    hic
                                    provident nulla repellat
                                    facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                    est
                                    sit pariatur.</p>
                </div>
              </div>
            <div class="row d-flex justify-content-center mb-4">
              <!-- col for event 1 -->
                            <div class="card mb-3 mr-5 ml-3" style="max-width:450px;max-height:450px;">
                                <img src="https://static.dribbble.com/users/1783758/screenshots/6386088/vinyl-record-and-cover-presentation-mock-up_2x.png" alt="no image found" width="450" height="450">
                                <div class="event-mask justify-content-center">
                                  <div class="row d-flex justify-content-center"> <h2 class="font-weight-bold" style="color:#ff5722;">About the Event</h2> </div>
                                  <div class="row d-flex justify-content-center">
                                    <div class="col">
                                    <p class="text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                                      hic
                                                      provident nulla repellat
                                                      facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                                      est
                                                      sit pariatur.</p>
                                      </div>
                                   </div>
                                   <div class="row d-flex justify-content-center">
                                     <a href="{% url 'user_login' %}" class="btn btn-primary mb-3" style="background-color:#ff5722;">Get Details</a>
                                   </div>
                                </div>
                            </div>
                            <!--col for event 2  -->
                            <div class="card mb-3 mr-5 ml-3" style="max-width: 450px;max-height:450px;">
                                <img src="https://c8.alamy.com/comp/2B8C4RC/debate-dialog-communication-and-education-concept-talking-about-political-opinions-two-cardboard-speech-bubbles-2B8C4RC.jpg" alt="no image found" width="450" height="450">
                                <div class="event-mask">
                                  <div class="row d-flex justify-content-center"> <h2 class="font-weight-bold" style="color:#ff5722;">About the Event</h2> </div>
                                  <div class="row d-flex justify-content-center">
                                      <div class="col">
                                          <p class="text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                                            hic
                                                            provident nulla repellat
                                                            facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                                            est
                                                            sit pariatur.</p>
                                        </div>
                                   </div>
                                   <div class="row d-flex justify-content-center">
                                     <a href="{% url 'user_login' %}" class="btn btn-primary mb-3" style="background-color:#ff5722;">Get Details</a>
                                   </div>
                                </div>
                            </div>
                    </div>

                            <!-- button to get all activities -->
                <div class="row d-flex justify-content-center mt-5 mb-3">
                    <a href="{% url 'user_login' %}" class="btn btn-primary mb-4" style="background-color:#ff5722;">See All Events</a>
            </div>
    </section>
  <hr class="my-5" style="color:#ff5722;">
</main>


{%endblock%}

sms_users/templates/sms_users/login.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
  {% csrf_token %}
  <label for="username">Username:</label>
  <input type="text" name="username" placeholder="Username" class="form-control">

  <label for="password">Password:</label>
  <input type="password" name="password" class="form-control">

    <input type="submit" value="Login">

</form>

{%endblock%}

sms_users/templates/sms_users/registration.html
{% extends 'base.html' %}

{% block content %}

{% if registered %}
    <h1>Thank you for registering</h1>
  {% else %}
      <h3>Fill the form: </h3>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form }}
        {{ profile_form }}
        <input type="submit" value="Register" class="btn btn-primary btn-block">
      </form>
  {% endif %}

{% endblock %}